version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install

  build:
    commands:
      - npm run docs:build

artifacts:
  files:
    - '**/*'
  # base-directory: 'docs/.vitepress/dist'

post_build:
  commands:
    # Sync the 'dist' folder with the S3 bucket
    - aws s3 sync docs/.vitepress/dist/ s3://thunder-vitepress-demo/